version: '3.8'
services:
  eda:
    build: ./
    env_file:
      - .env
    # user: root
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    # command: chainlit run main.py --host 0.0.0.0
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8000
  